import './globals.css'
import {Taskprovider} from '../context/TasksContext'
import { Inter } from 'next/font/google'
import { NavBar } from '@/components/NavBar'
import { Toaster } from './Toaster'
import { Layout } from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Task App by NextJs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <Taskprovider>
          <NavBar/>
          <Layout>{children}</Layout>
          <Toaster/>
        </Taskprovider>
      </body>
    </html>
  )
}
